language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
